import { type Note, noteName } from "@/domain/notes";
import { transposeNote } from "@/domain/intervals";
import { relativeKey, type Key } from "@/domain/keys";

export interface KeyOption {
  key: Key;
  /** e.g. "C" or "Am" — the tonic's spelled name plus "m" for minor. */
  label: string;
  id: string;
}

/**
 * A canonical id for a key ("C", "Am", ...) — exported so callers holding a
 * `Key` value (never reference-equal to the ones in `listKeyOptions()`,
 * since it's a plain object) can look up the matching option by identity
 * instead of `===`.
 */
export function keyOptionId(key: Key): string {
  return key.mode === "major" ? noteName(key.tonic) : `${noteName(key.tonic)}m`;
}

function toOption(key: Key): KeyOption {
  const id = keyOptionId(key);
  return { key, label: id, id };
}

/**
 * The 12 conventional major keys, generated by walking the circle of fifths
 * from C (never hardcoded per key) — ascending fifths for the sharp side,
 * descending fifths for the flat side, meeting at the standard 12
 * enharmonic spellings (no double-sharp/double-flat keys in this list).
 */
function generateMajorTonics(): Note[] {
  const tonics: Note[] = [{ letter: "C", accidental: 0 }];
  let sharpSide = tonics[0];
  for (let i = 0; i < 6; i++) {
    sharpSide = transposeNote(sharpSide, 7);
    tonics.push(sharpSide);
  }
  let flatSide = tonics[0];
  for (let i = 0; i < 5; i++) {
    flatSide = transposeNote(flatSide, -7);
    tonics.push(flatSide);
  }
  return tonics;
}

/**
 * Every selectable key for Phase 4's tonal-context picker: the 12 major keys
 * plus their relative natural minors (via ../../domain/keys' `relativeKey`,
 * not hardcoded), sorted by ascending root pitch class then mode so the list
 * order is stable.
 */
export function listKeyOptions(): KeyOption[] {
  const majorKeys: Key[] = generateMajorTonics().map((tonic) => ({ tonic, mode: "major" as const }));
  const minorKeys: Key[] = majorKeys.map((key) => relativeKey(key));

  return [...majorKeys, ...minorKeys].map(toOption);
}
